# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20161003_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='one_time_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='one_time_code_active_time',
        ),
    ]
